__author__ = "Jonas Almlöf"
__copyright__ = "Copyright 2021, Jonas Almlöf"
__email__ = "jonas.almlof@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/extract_reads.smk"
include: "rules/bwa_mem.smk"
include: "rules/mark_duplicates.smk"
include: "rules/samtools_index.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
