# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Patrik Smeds"
__copyright__ = "Copyright 2021, Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"

include: "rules/common.smk"
include: "rules/bwa-mem.smk"

report: "report/workflow.rst"

rule all:
    input:
        unpack(compile_output_list),
