samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"
  dict: "reference/WASH7P.dict"
  fna: "reference/WASH7P.fna"
  amb: "reference/WASH7P.fna.amb"
  ann: "reference/WASH7P.fna.ann"
  bwt: "reference/WASH7P.fna.bwt"
  fai: "reference/WASH7P.fna.fai"
  pac: "reference/WASH7P.fna.pac"
  sa: "reference/WASH7P.fna.sa"

bwa_mem:
  container: "docker://gmsuppsala/somatic:develop"

bqsr_gpu:
  known_indels: Mills_and_1000G_gold_standard.indels.vcf.gz #Homo_sapiens_assembly38.known_indels.vcf.gz
