samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://hydragenetics/common:0.1.3"

reference:
  fasta: "reference/WASH7P.fna"
  fai: "reference/WASH7P.fna.fai"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  amb: "reference/WASH7P.fna.amb"
  ann: "reference/WASH7P.fna.ann"
  bwt: "reference/WASH7P.fna.bwt"
  pac: "reference/WASH7P.fna.pac"
  sa: "reference/WASH7P.fna.sa"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

star:
  container: "docker://hydragenetics/star:2.7.10a"
  genome_index: "reference/star_idx"

trimmer_software: "fastp_pe"
