samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"

bwa_mem:
  container: "docker://gmsuppsala/somatic:develop"
  params:
    extra: r"-R '@RG\tID:{sample}\tSM:{sample}\tPL:illumina\tPU:{sample} -v 1 '"

bqsr_gpu:
  known_indels: Mills_and_1000G_gold_standard.indels.vcf.gz #Homo_sapiens_assembly38.known_indels.vcf.gz
