samples: "samples_pacbio.tsv"
units: "units_pacbio.tsv"
resources: "resources_longread.yaml"

default_container: "docker://hydragenetics/common:1.14.0"

reference:
  fasta: "reference/WASH7P.fasta"
  fai: "reference/WASH7P.fasta.fai"

vacmap_align:
  mode: "L"
  container: "docker://hydragenetics/vacmap:1.0.0"
