samples: "samples_pacbio.tsv"
units: "units_pacbio.tsv"
resources: "resources.yaml"

longread_alignment: true
pacbio_alignment: true

default_container: "docker://hydragenetics/common:1.14.0"

reference:
  fasta: "reference/WASH7P.fna"
  fai: "reference/WASH7P.fna.fai"
  skip_contigs: # contigs to be skipped during mark duplicates and excluded from merged bam
    - "chrM"
  merge_contigs: # contigs to be merged to a single BAM for mark duplicates
    - ".*_random"
    - ".chrUn*"

hifiasm:
  container: "docker://hydragenetics/hifiasm:0.19.8"
  extra: ""

minimap2:
  mmi: "reference/WASH7P.hifi.mmi"
  preset: "map-hifi"
  container: "docker://hydragenetics/minimap2:2.26"

pbmm2_align:
  index: "reference/WASH7P.hifi.mmi"
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.10"

pbmm2_samtools_sort:
  extra: "--threads 10 -l 9 -m 4G"  # set threads 10, best compression rate l, and maximum mem per thread  m 4G
  container: "docker://hydragenetics/common:1.14.0"

pbmm2_samtools_index:
  extra: "--threads 10 -l 9 -m 4G"  # set threads 10, best compression rate l, and maximum mem per thread  m 4G
  container: "docker://hydragenetics/common:1.14.0"

