samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"

bqsr_GPU:
  known_indels: "reference/known_indels.vcf.gz"
