samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

software:
  align: "align_dedup_GPU" #"bwa_mem"
  dedup: "align_dedup_GPU" #"mark_duplicates"


default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"
