name: small integration test

on:
  push:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install apptainer/singularity
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa && sudo apt install -y software-properties-common && sudo apt install -y apptainer-suid
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Integration test illumina - small dataset
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile -j 1 --show-failed-logs --configfiles config.yaml config_fastp_pe.yaml --show-failed-logs --use-singularity --singularity-args  " --cleanenv --bind /home/runner "
      - name: Integration test longread - small dataset 
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile -j 1 --show-failed-logs --configfiles config_longread.yaml --show-failed-logs --use-singularity --singularity-args  " --cleanenv --bind /home/runner "
