name: small integration test

on:
  push:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  integration-small-conda:
    name: integration small data set conda
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true
      - name: Install dependencies
        run: |
          conda config --set channel_priority strict
          mamba install -c conda-forge -c bioconda python=3.8
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Integration test - small dataset
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile -j 1 --show-failed-logs --use-conda --configfiles config.yaml config_fastp_pe.yaml
  integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true
      - name: Install dependencies
        run: |
          conda config --set channel_priority strict
          mamba install -c conda-forge -c bioconda singularity=3.8.6 python=3.8
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Integration test - small dataset
        working-directory: .tests/integration
        run: |
          snakemake -s ../../workflow/Snakefile -j 1 --show-failed-logs --configfiles config.yaml config_fastp_pe.yaml --show-failed-logs --use-singularity --singularity-args  " --cleanenv --bind /home/runner "
