name: Snakemake dry run

on:
  push:
    branches:
     - develop
     - master
  pull_request:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: Run snakemake dry run
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
          pip install -r docs/requirements.txt
      - name: snakemake dry run
        run: |
          mkdocs build
