name: build mkdocs

on:
  push:
    branches:
     - develop
     - master
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements*.txt"
      - ".github/workflows/**"
      - "workflow/rules/**"
      - "workflow/schemas/**"
  pull_request:
    branches:
     - develop
     - master
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements*.txt"
      - ".github/workflows/**"
      - "workflow/rules/**"
      - "workflow/schemas/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mkdocs:
    name: build mkdocs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: |            
            docs/requirements.txt
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: build mkdocs
        run: |
          mkdocs build
