samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

trimmer_software: "fastp_pe"

default_container: "docker://hydragenetics/common:0.1.1"

reference:
  fasta: "../integration/reference/WASH7P.fna"
  fai: "../integration/reference/WASH7P.fna.fai"
  skip_contigs: # contigs to be skipped during mark duplicates and excluded from merged bam
    - "chrM"
  merge_contigs: # contigs to be merged to a single BAM for mark duplicates
    - ".*_random"
    - ".chrUn*"

bwa_mem:
  amb: "../integration/reference/WASH7P.fna.amb"
  ann: "../integration/reference/WASH7P.fna.ann"
  bwt: "../integration/reference/WASH7P.fna.bwt"
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  pac: "../integration/reference/WASH7P.fna.pac"
  sa: "../integration/reference/WASH7P.fna.sa"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"
